Lab 8/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab_8.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Lab_8.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private RoleManager<IdentityRole> _RoleManager;
        private UserManager<CustomIdentityUser> _UserManager;

        public AdminController(RoleManager<IdentityRole> roleManager, UserManager<CustomIdentityUser> userManager)
        {
            _RoleManager = roleManager;
            _UserManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateRole(string RoleName)
        {
            IdentityRole role = new IdentityRole
            {
                Name = RoleName
            };
            IdentityResult identityResult = _RoleManager.CreateAsync(role).Result;
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteRole(string RoleName)
        {
            IdentityRole role = _RoleManager.FindByNameAsync(RoleName).Result;
            IdentityResult identityResult = _RoleManager.DeleteAsync(role).Result;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddUserToRole(string Email)
        {
            return View("AddUserToRole", Email);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUserToRole(string Email, string RoleName)
        {
            CustomIdentityUser identityUser = _UserManager.FindByEmailAsync(Email).Result;
            IdentityResult identityResult = _UserManager.AddToRoleAsync(identityUser, RoleName).Result;

            if (!identityResult.Succeeded)
            {
                throw new Exception(identityResult.Errors.Select(e => e.Description).Aggregate((a, b) => a + "," + b));
            }

            return RedirectToAction("Index");
        }
    }
}

Lab 8/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width" />
    <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js"></script>
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/css/DefaultStyles.css")" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <h1 class="navbar-brand">Lab 8</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-item nav-link" })
                    @Html.ActionLink("Roles", "Index", "Admin", null, new { @class = "nav-item nav-link" })
                </div>
                <div class="ml-auto">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <main>
            <div class="row">
                <div class="col-sm-12">
                    @RenderBody()
                </div>
            </div>
        </main>
        <footer class="page-footer font-small text-light">
            <div class="footer-copyright text-center py-3">
                © 2018 Copyright:
                <a href="http://www.oit.edu"> www.oit.edu</a>
            </div>
        </footer>
    </div>
</body>
</html>

@RenderSection("Scripts", required: false)