Lab 4/Models/ComputerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_4.Models
{
    public class ComputerModel
    {
        public static readonly List<string> OSTypes =
            new List<string> { "iOS", "Windows", "Linux" };

        [Required]
        [MaxLength(20)]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string Password { get; set; }
        [RegularExpression("\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}", 
            ErrorMessage = "IP Address must be one to three digits before and after each of the three dots. Ex. 127.0.0.1")]
        [DisplayName("IP Address")]
        public string IPAddress { get; set; }
        [DisplayName("Location")]
        public string Location { get; set; }
        [Required]
        [UIHint("OSDropdown")]
        [DisplayName("OS")]
        public string OS { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("Description")]
        public string Description { get; set; }
        [Required]
        [Range(1, 4)]
        [DisplayName("Supported Monitors")]
        public int? SupportedMonitors { get; set; }
    }
}

Lab 4/Controllers/HHEditorForController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HHEditorForController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Controllers/HHEditorForModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HHEditorForModelController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Controllers/HHInputController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HHInputController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Controllers/HHInputForController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HHInputForController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Lab_4.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lab 4/Controllers/StandardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab_4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab_4.Controllers
{
    public class StandardController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Controllers/TagHelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class TagHelperController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ComputerModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(ComputerModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View(new ComputerModel());
            }
            return View("Submission", model);
        }
    }
}

Lab 4/Views/HHEditorForModel/Index.cshtml
@model ComputerModel

@{
    ViewData["Title"] = "Index";
}

<h2>HHEditorForModel</h2>

@Html.EditorForModel()

Lab 4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Project Description</h2>

<br />

<p>
    Those are forms that are made by different types.
</p>
<p>
    Standard - The views for this controller will use plain HTML labels and inputs. Validation messages are not required for this.
</p>
<p>
    HHInput - The index view for this controller will use HTML Helpers to generate the form labels/inputs.
</p>
<p>
    HHInputFor - This is similar to the views for HHInputController.
</p>
<p>
    HHEditorFor - This is similar to the views for HHInputForController.
</p>
<p>
    HHEditorForModel - This will use the EditorForModel HTML helper in order to automatically generate the form.
</p>
<p>
    TagHelper - This will use Tag Helpers in order to generate the form controls.
</p>

Lab 4/Views/Shared/DisplayTemplates/ComputerModel.cshtml
@model ComputerModel

<div>
    <span>Name: </span>@Model.Name
</div>
<div>
    <span>Password: </span>@Model.Password
</div>
<div>
    <span>IP Address: </span>@Model.IPAddress
</div>
<div>
    <span>Location: </span>@Model.Location
</div>
<div>
    <span>OS: </span>@Model.OS
</div>
<div>
    <span>Description: </span>@Model.Description
</div>
<div>
    <span>Supported Monitor: </span>@Model.SupportedMonitors
</div>

Lab 4/Views/TagHelper/Index.cshtml
@model ComputerModel

@{
    ViewData["Title"] = "Index";
}

<h2>TagHelper</h2>

<form method="post" asp-action="Index" asp-controller="TagHelper">

    @Html.AntiForgeryToken()

    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input type="text" asp-for="Name" placeholder="Enter your name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input type="password" asp-for="Password" placeholder="Enter password" class="form-control" />
        <span asp-validation-for="Password"></span>
    </div>
    <div class="form-group">
        <label asp-for="IPAddress" class="control-label"></label>
        <input type="text" asp-for="IPAddress" placeholder="Enter IP address" class="form-control" />
        <span asp-validation-for="IPAddress"></span>
    </div>
    <div class="form-group">
        <label asp-for="Location" class="control-label"></label>
        <input type="text" asp-for="Location" placeholder="Enter location" class="form-control" />
        <span asp-validation-for="Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="OS" class="control-label"></label>
        <select asp-for="OS" asp-items="new SelectList(ComputerModel.OSTypes)" class="form-control">
            <option selected value="">--- Select an OS ---</option>
        </select>
        <span asp-validation-for="OS"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" rows="5" placeholder="Enter description" class="form-control"></textarea>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="SupportedMonitors" class="control-label"></label>
        <input type="number" asp-for="SupportedMonitors" placeholder="Enter a number" class="form-control" />
        <span asp-validation-for="SupportedMonitors"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>